/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zero_licht_androidfmod_EffectUtils */

#ifndef _Included_com_zero_licht_androidfmod_EffectUtils
#define _Included_com_zero_licht_androidfmod_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zero_licht_androidfmod_EffectUtils
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_EffectUtils_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
