/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zero_licht_androidfmod_MainActivity */

#ifndef _Included_com_zero_licht_androidfmod_MainActivity
#define _Included_com_zero_licht_androidfmod_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    getButtonLabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zero_licht_androidfmod_MainActivity_getButtonLabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    buttonDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_buttonDown
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    buttonUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_buttonUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    setStateCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_setStateCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    setStateStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_setStateStart
  (JNIEnv *, jobject);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    setStateStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_setStateStop
  (JNIEnv *, jobject);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    setStateDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_setStateDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_zero_licht_androidfmod_MainActivity
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_androidfmod_MainActivity_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
